"""add topics, topic_progress, topic_id on session/quiz

Revision ID: 210c14dbf05f
Revises: c50ffe83d18c
Create Date: 2026-07-12 01:39:08.773644
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '210c14dbf05f'
down_revision: Union[str, None] = 'c50ffe83d18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _add_column_if_not_exists(table: str, column: sa.Column) -> None:
    try:
        op.add_column(table, column)
    except Exception as e:
        if "duplicate column" in str(e).lower() or "already exists" in str(e).lower():
            pass
        else:
            raise


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('topics',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('subject', sa.String(length=100), nullable=False),
        sa.Column('exam_tag', sa.String(length=100), nullable=True),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_topics_subject'), 'topics', ['subject'], unique=False)
    except Exception as e:
        if "already exists" in str(e).lower():
            pass
        else:
            raise
    try:
        op.create_table('user_topic_progress',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('topic_id', sa.Uuid(), nullable=False),
        sa.Column('questions_answered', sa.Integer(), nullable=False),
        sa.Column('correct', sa.Integer(), nullable=False),
        sa.Column('accuracy', sa.Float(), nullable=False),
        sa.Column('study_minutes', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_user_topic_progress_topic_id'), 'user_topic_progress', ['topic_id'], unique=False)
        op.create_index(op.f('ix_user_topic_progress_user_id'), 'user_topic_progress', ['user_id'], unique=False)
    except Exception as e:
        if "already exists" in str(e).lower():
            pass
        else:
            raise
    _add_column_if_not_exists('quiz_sessions', sa.Column('topic_id', sa.Uuid(), nullable=True))
    _add_column_if_not_exists('sessions', sa.Column('topic_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'topic_id')
    op.drop_column('quiz_sessions', 'topic_id')
    op.drop_index(op.f('ix_user_topic_progress_user_id'), table_name='user_topic_progress')
    op.drop_index(op.f('ix_user_topic_progress_topic_id'), table_name='user_topic_progress')
    op.drop_table('user_topic_progress')
    op.drop_index(op.f('ix_topics_subject'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
