"""add daily_study_target_minutes

Revision ID: c50ffe83d18c
Revises: 0003
Create Date: 2026-07-07 23:51:10.170234
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c50ffe83d18c'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def _add_column_if_not_exists(table, column):
    try:
        _add_column_if_not_exists(table, column)
    except Exception as e:
        if 'duplicate column' in str(e).lower() or 'already exists' in str(e).lower():
            pass
        else:
            raise


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _add_column_if_not_exists('users', sa.Column('daily_study_target_minutes', sa.Integer(), nullable=False, server_default='120'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_study_target_minutes')
    # ### end Alembic commands ###
